predictions/urls.py
from django.conf.urls import url

"""predictions_app URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from . import views

app_name = 'predictions'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^events/(?P<event_id>.+)/$', views.event, name='event'),
    url(r'^webhook/$', views.webhook, name='webhook')
]

predictions_app/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
                  url(r'^', include('predictions.urls')),
                  url(r'^admin/', admin.site.urls)
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

predictions/models.py
from django.db import models


# Create your models here.
class Team(models.Model):
    team_id = models.CharField("Team ID", max_length=10, primary_key=True)
    auto_fuel = models.FloatField("Auto Fuel OPR")
    auto_rotor = models.FloatField("Auto Rotor OPR")
    teleop_fuel = models.FloatField("Teleop Fuel OPR")
    teleop_rotor = models.FloatField("Teleop Rotor OPR")
    teleop_takeoff = models.FloatField("Teleop Takeoff OPR")

    def __str__(self):
        return self.team_id


class Event(models.Model):
    EVENT_TYPES = (
        (0, 'Regional'),
        (1, 'District Qualifier'),
        (2, 'District Championship'),
        (3, 'Championship Division'),
        (4, 'Championship Finals'),
        (99, 'Offseason'),
        (100, 'Preseason'),
        (-1, 'Other')
    )

    DISTRICTS = (
        ('0', 'No District'),
        ('fim', 'Michigan'),
        ('mar', 'Mid-Atlantic'),
        ('ne', 'New England'),
        ('pnw', 'Pacifc Northwest'),
        ('in', 'Indiana'),
        ('chs', 'Chesapeake'),
        ('nc', 'North Carolina'),
        ('pch', 'Georgia'),
        ('ont', 'Ontario'),
        ('isr', 'Israel'),
    )

    event_id = models.CharField("Event ID", max_length=16, primary_key=True)
    name = models.CharField("Event Name", max_length=255)
    week = models.IntegerField("Event Week")
    type = models.IntegerField("Event Type", choices=EVENT_TYPES)
    district = models.CharField("District", choices=DISTRICTS, max_length=3, null=True)

    def __str__(self):
        return self.name + ' (' + self.event_id + ')'


class Match(models.Model):
    class Meta:
        verbose_name_plural = "matches"

    ROUNDS = (
        ('qm', 'Qualification'),
        ('ef', 'Octofinal'),
        ('qf', 'Quarterfinal'),
        ('sf', 'Semifinal'),
        ('f', 'Final')
    )

    match_id = models.CharField("Match / Alliance ID", max_length=64, primary_key=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='matches')
    match_num = models.CharField("Match #", max_length=8)
    round = models.CharField("Round", max_length=2, choices=ROUNDS)
    alliance = models.BooleanField("Red Alliance?")
    score = models.IntegerField("Match Score")
    kpa = models.NullBooleanField("40 KPA Reached?", blank=True, null=True, default=None)
    rotor = models.NullBooleanField("4 Rotors Active?", blank=True, null=True, default=None)

    team1 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='matches1')
    team2 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='matches2')
    team3 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='matches3')

    def name(self) -> str:
        clean_number = self.match_num.replace(self.round, '')
        if self.round == 'qm':
            return 'Qual. ' + clean_number
        else:
            set, num = clean_number.split('m')
            if self.round == 'f':
                return 'Finals ' + num
            elif self.round == 'sf':
                return 'Semi. ' + set + ' Match ' + num
            elif self.round == 'qf':
                return 'Quarter. ' + set + ' Match ' + num
            elif self.round == 'ef':
                return 'Octo. ' + set + ' Match ' + num

    def sort_key(self):
        rounds = {'f': 5000, 'sf': 4000, 'qf': 2000, 'ef': 1000, 'qm': 0}
        clean_number = self.match_num.replace(self.round, '')
        if self.round == 'qm':
            r = int(clean_number) + (0.5 if not self.alliance else 0)
            return r
        else:
            set, num = clean_number.split('m')
            r = rounds[self.round] + 100 * int(set) + int(num) + (0.5 if not self.alliance else 0)
            return r

    def __str__(self):
        return self.match_id

predictions/views.py
import json

from django.db import transaction
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from predictions import frc
from predictions.models import Event, Match


def index(request):
    event_list = Event.objects.order_by('week').filter()
    context = {
        'event_list': event_list.filter(week__lte=4)
    }
    return render(request, 'predictions/index.html', context)


def event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    matches = frc.get_matches(event, 'force' in request.GET)
    context = {
        'event': event,
        'matches': sorted(frc.make_predictions(matches), key=lambda m: m[0].sort_key())
    }
    return render(request, 'predictions/event.html', context)


@csrf_exempt
@require_POST
def webhook(request):
    content = json.loads(request.body)
    message_type = content['message_type']
    print(message_type)
    if message_type == 'match_score':
        m = content['message_data']
        event = get_object_or_404(Event, pk=m['event_key'])
        m = m['match']
        with transaction.atomic():
            for color in ['red', 'blue']:
                match_id = m['key'] + '_' + color
                match_num = m['key'].split('_')[1]
                round = m['comp_level']
                alliance = color == 'red'

                if m['score_breakdown'] is not None:
                    score = m['score_breakdown'][color]
                    kpa = (score['kPaBonusPoints'] > 0 or score['kPaRankingPointAchieved'])
                    rotor = (score['rotorBonusPoints'] > 0 or score['rotorRankingPointAchieved'])
                else:
                    kpa = None
                    rotor = None

                allies = m['alliances'][color]['teams']
                team1 = frc.get_team(allies[0])
                team2 = frc.get_team(allies[1])
                team3 = frc.get_team(allies[2])
                score = m['alliances'][color]['score']

                match = Match(match_id=match_id, event=event, match_num=match_num, round=round, alliance=alliance,
                              score=score, kpa=kpa, rotor=rotor, team1=team1, team2=team2, team3=team3)
                match.save()
        return HttpResponse("OK")
    elif message_type == "schedule_updated":
        m = content['message_data']
        event = get_object_or_404(Event, pk=m['event_key'])
        frc.get_matches(event, force=True)
        return HttpResponse("OK")
    else:
        raise Http404

templates/predictions/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Predictions{% endblock %}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'predictions/style.css' %}"/>
</head>
<body>
<main class="mdl-layout__content">
    {% block header %}
        <h1>Homepage</h1>
    {% endblock %}
    <div><a href="{% url 'predictions:index' %}">Return to Index</a></div>
    <div class="page-content">
        {% block main %}
            <a href="{% url 'predictions:index' %}">Return to Index</a>
        {% endblock %}
    </div>
</main>
</body>
</html>

templates/predictions/event.html
{% extends "predictions/_base.html" %}
{% block title %}Predictions for {{ event.name }}{% endblock %}
{% block header %}<h1>{{ event.name }}</h1>{% endblock %}
{% block main %}
    <div class="mdl-grid">
        <table class="mdl-cell mdl-cell--6-col matches-table">
            <thead>
            <tr>
                <th class=>Match</th>
                <th colspan="3" class>Teams</th>
                <th>Score</th>
                <th>Predicted Score</th>
                <th>Win Prob. %</th>
            </tr>
            </thead>
            <tbody>
            {% for match_pred in matches %}
                <tr class="{% if match_pred.0.alliance %}red-row{% else %}blue-row{% endif %}">
                    {% if match_pred.0.alliance %}
                        <td rowspan="2" class="match-name-col">{{ match_pred.0.name }}</td>
                    {% endif %}
                    <td class="team-col">{{ match_pred.0.team1.team_id }}</td>
                    <td class="team-col">{{ match_pred.0.team2.team_id }}</td>
                    <td class="team-col">{{ match_pred.0.team3.team_id }}</td>
                    {% if match_pred.0.score > -1 %}
                        <td class="score-col">{{ match_pred.0.score }}</td>
                    {% else %}
                        <td>?</td>
                    {% endif %}
                    <td class="pred-score-col">{{ match_pred.1|floatformat }}</td>
                    <td class="win-prob-col">{{ match_pred.2|floatformat }}%</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/predictions/index.html
{% extends "predictions/_base.html" %}

{% block main %}
    {% if event_list %}
        <ul>
            {% for event in event_list %}
                <li>{{ event.event_id }} - <a href="{% url 'predictions:event' event.event_id %}">{{ event.name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Hmmm, no events are available. Check back later.</p>
    {% endif %}
{% endblock %}